from pathlib import Path

FMT= '%Y-%m-%dT%H:%M:%S'

RUN_SCRIPT_NAME = 'run'
RUNS_DIR = 'runs'
STATE_FILE = '_STATE'
OUT_FILE = '_OUT'
MSG_PATH = Path('_MSG')

DEFAULT_UPSTREAM_BRANCH = 'master'
RUNS_REMOTE = 'runs'
RUNS_BRANCH = 'runs'

SUCCESS_PATH = 'SUCCESS'
FAILURE_PATH = 'FAILURE'

LOGS_DIR = Path('logs')
OUT_PATH = LOGS_DIR / 'out'
ERR_PATH = LOGS_DIR / 'err'

EARLY_EXIT_EXCEPTION_MSG_PREFIX = 'OK: '

CRON_MODULE_RC = '.cron-module-rc'
CRON_MODULE_RC_ENV = 'CRON_MODULE_RC'

LOCK_TIMEOUT_DEFAULT_S = 600
EXECUTION_TIMEOUT_DEFAULT_S = 600
